#### Buildinig Model for spam detector 

In [9]:
!pip install nltk 

In [11]:
## nltk(natural language toolkit) - > Library for NLP

In [12]:
import nltk

In [13]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

### Basic Intro code 

In [14]:
text = """Natural language processing (NLP) is the ability of a computer 
        program to understand human language as it is spoken and written -- referred to as natural language. ... NLP has existed for more than 50 years and has roots in the field of linguistics."""

In [15]:
text

'Natural language processing (NLP) is the ability of a computer \n        program to understand human language as it is spoken and written -- referred to as natural language. ... NLP has existed for more than 50 years and has roots in the field of linguistics.'

## pipe line for Natural Language processing  

1 . Data Preprocessing 
      
        a . Data clearning(Removing Puncutations)
        b . Lower the data 
        c . Removing Stopwords
        d . Stemming
        e . lemmatization

### cleaning data 

In [16]:
import string 


In [17]:
string = string.punctuation

In [18]:
text

'Natural language processing (NLP) is the ability of a computer \n        program to understand human language as it is spoken and written -- referred to as natural language. ... NLP has existed for more than 50 years and has roots in the field of linguistics.'

In [19]:
text_clear = []
for i in text:
    if i not in string:
        text_clear.append(i)
text_clear_data = "".join(text_clear)

In [20]:
text_clear_data

'Natural language processing NLP is the ability of a computer \n        program to understand human language as it is spoken and written  referred to as natural language  NLP has existed for more than 50 years and has roots in the field of linguistics'

In [21]:
import re

#### Tokenization 

            a . sent_tokenize
            b . word_tokenize

In [22]:
from nltk.tokenize import sent_tokenize

In [23]:
text_clear_data = nltk.sent_tokenize(text_clear_data)

In [24]:
text_clear_data

['Natural language processing NLP is the ability of a computer \n        program to understand human language as it is spoken and written  referred to as natural language  NLP has existed for more than 50 years and has roots in the field of linguistics']

In [25]:
for j in range(len(text_clear_data)):
    text_clear_data = re.sub("[^a-zA-Z0-9]"," ",text_clear_data[j])

In [26]:
text_clear_data = re.sub(r'\s+',' ',text_clear_data)

In [27]:
text_clear_data

'Natural language processing NLP is the ability of a computer program to understand human language as it is spoken and written referred to as natural language NLP has existed for more than 50 years and has roots in the field of linguistics'

### Lower the text

In [28]:
text_clear_data_lower = text_clear_data.lower()

In [29]:
text_clear_data_lower

'natural language processing nlp is the ability of a computer program to understand human language as it is spoken and written referred to as natural language nlp has existed for more than 50 years and has roots in the field of linguistics'

### Applying stopwords

In [30]:
from nltk.corpus import stopwords

In [31]:
print(stopwords.words("english"))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [32]:
text_clear_data_stopwords = text_clear_data_lower.split()

In [33]:
text_clear_data_stopwords[:10]

['natural',
 'language',
 'processing',
 'nlp',
 'is',
 'the',
 'ability',
 'of',
 'a',
 'computer']

In [34]:
s_w = []
for k in text_clear_data_stopwords:
    if k not in stopwords.words("english"):
        s_w.append(k)
s_w = " ".join(s_w)

In [35]:
s_w

'natural language processing nlp ability computer program understand human language spoken written referred natural language nlp existed 50 years roots field linguistics'

### stemming 

In [36]:
from nltk.stem import PorterStemmer

In [37]:
stemming = PorterStemmer()

In [38]:
s_w_s = s_w.split()

In [39]:
s_w_s[:10]

['natural',
 'language',
 'processing',
 'nlp',
 'ability',
 'computer',
 'program',
 'understand',
 'human',
 'language']

In [40]:
stem = []

for l in s_w_s:
    print("Actual keyword : ",l ,"stemming keyword : ",stemming.stem(l))
    stem.append(stemming.stem(l))
stem = " ".join(stem)    
    


Actual keyword :  natural stemming keyword :  natur
Actual keyword :  language stemming keyword :  languag
Actual keyword :  processing stemming keyword :  process
Actual keyword :  nlp stemming keyword :  nlp
Actual keyword :  ability stemming keyword :  abil
Actual keyword :  computer stemming keyword :  comput
Actual keyword :  program stemming keyword :  program
Actual keyword :  understand stemming keyword :  understand
Actual keyword :  human stemming keyword :  human
Actual keyword :  language stemming keyword :  languag
Actual keyword :  spoken stemming keyword :  spoken
Actual keyword :  written stemming keyword :  written
Actual keyword :  referred stemming keyword :  refer
Actual keyword :  natural stemming keyword :  natur
Actual keyword :  language stemming keyword :  languag
Actual keyword :  nlp stemming keyword :  nlp
Actual keyword :  existed stemming keyword :  exist
Actual keyword :  50 stemming keyword :  50
Actual keyword :  years stemming keyword :  year
Actual ke

In [41]:
stem

'natur languag process nlp abil comput program understand human languag spoken written refer natur languag nlp exist 50 year root field linguist'

### Lemmatization

In [42]:
from nltk.stem import WordNetLemmatizer
lemmatize = WordNetLemmatizer()

In [43]:
s_w_s[:10]

['natural',
 'language',
 'processing',
 'nlp',
 'ability',
 'computer',
 'program',
 'understand',
 'human',
 'language']

In [55]:
lemm = []

for p in s_w_s:
    print("Actual keyword : ",p ,"Lemmatization keyword : ",lemmatize.lemmatize(p))
    lemm.append(lemmatize.lemmatize(p))

lemm= " ".join(lemm)    
    


Actual keyword :  natural Lemmatization keyword :  natural
Actual keyword :  language Lemmatization keyword :  language
Actual keyword :  processing Lemmatization keyword :  processing
Actual keyword :  nlp Lemmatization keyword :  nlp
Actual keyword :  ability Lemmatization keyword :  ability
Actual keyword :  computer Lemmatization keyword :  computer
Actual keyword :  program Lemmatization keyword :  program
Actual keyword :  understand Lemmatization keyword :  understand
Actual keyword :  human Lemmatization keyword :  human
Actual keyword :  language Lemmatization keyword :  language
Actual keyword :  spoken Lemmatization keyword :  spoken
Actual keyword :  written Lemmatization keyword :  written
Actual keyword :  referred Lemmatization keyword :  referred
Actual keyword :  natural Lemmatization keyword :  natural
Actual keyword :  language Lemmatization keyword :  language
Actual keyword :  nlp Lemmatization keyword :  nlp
Actual keyword :  existed Lemmatization keyword :  exist

In [56]:
lemm

'natural language processing nlp ability computer program understand human language spoken written referred natural language nlp existed 50 year root field linguistics'

### Converting words into vectors 

Vector_Representation

         a . one_hot_encoding
         b . Bag_of_words
         c . TF_IDF
         d . word_Embeddings
                1 . Word_2_vec
                2 . Glove
      

### one_hot_encoding

In [64]:
import tensorflow.keras

In [66]:
from tensorflow.keras.preprocessing.text import one_hot

In [67]:
cv = CountVectorizer()

In [69]:
lemm

'natural language processing nlp ability computer program understand human language spoken written referred natural language nlp existed 50 year root field linguistics'

In [70]:
lemm = lemm.split()

In [72]:
lemm[:5]

['natural', 'language', 'processing', 'nlp', 'ability']

In [73]:
X = cv.fit_transform(lemm)

In [74]:
X

<22x18 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>

In [75]:
cv.vocabulary_

{'natural': 8,
 'language': 6,
 'processing': 10,
 'nlp': 9,
 'ability': 1,
 'computer': 2,
 'program': 11,
 'understand': 15,
 'human': 5,
 'spoken': 14,
 'written': 16,
 'referred': 12,
 'existed': 3,
 '50': 0,
 'year': 17,
 'root': 13,
 'field': 4,
 'linguistics': 7}

In [76]:
X.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

### Bag of words

In [78]:
a = """data science engineering.
Artificial Intelligence .
machine learning Deep processing"""

In [79]:
a

'data science engineering.\nArtificial Intelligence .\nmachine learning Deep processing'

In [80]:
a = sent_tokenize(a)

In [81]:
a

['data science engineering.',
 'Artificial Intelligence .',
 'machine learning Deep processing']

In [82]:
list = []
for i in range(len(a)):
    solution = re.sub("[^a-zA-Z]", " ", a[i])
    solution = solution.lower()
    solution = solution.split()
    solution = [lemmatize.lemmatize(k) for k in solution if k not in set(stopwords.words('english'))]
    solution = " ".join(solution)
    list.append(solution)

In [83]:
list

['data science engineering',
 'artificial intelligence',
 'machine learning deep processing']

In [84]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [85]:
X = cv.fit_transform(list).toarray()

In [86]:
X

array([[0, 1, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 1, 1, 0]], dtype=int64)

### TF_IDF

In [90]:
tf = """data science engineering.
Artificial Intelligence .
machine learning Deep processing"""

In [92]:
tf = sent_tokenize(tf)

In [93]:
tf

['data science engineering.',
 'Artificial Intelligence .',
 'machine learning Deep processing']

In [94]:
list = []
for i in range(len(tf)):
    solution = re.sub("[^a-zA-Z]", " ", tf[i])
    solution = solution.lower()
    solution = solution.split()
    solution = [lemmatize.lemmatize(k) for k in solution if k not in set(stopwords.words('english'))]
    solution = " ".join(solution)
    list.append(solution)

In [95]:
list

['data science engineering',
 'artificial intelligence',
 'machine learning deep processing']

In [96]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [97]:
tf = TfidfVectorizer()

In [98]:
f = tf.fit_transform(list)

In [100]:
tf.vocabulary_

{'data': 1,
 'science': 8,
 'engineering': 3,
 'artificial': 0,
 'intelligence': 4,
 'machine': 6,
 'learning': 5,
 'deep': 2,
 'processing': 7}

In [102]:
f.toarray()

array([[0.        , 0.57735027, 0.        , 0.57735027, 0.        ,
        0.        , 0.        , 0.        , 0.57735027],
       [0.70710678, 0.        , 0.        , 0.        , 0.70710678,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.5       , 0.5       , 0.5       , 0.        ]])

### word_Embeddings

In [107]:
import tensorflow as tf

In [108]:
print(tf.__version__)

2.3.0


In [109]:
import tensorflow.keras as tf

In [110]:
import tensorflow as tf

In [111]:
from tensorflow.keras.preprocessing.text import one_hot

In [112]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [113]:
docs = ['Well done!',
'Good work',
'Great effort',
'nice work',
'Excellent!',
'Weak',
'Poor effort!',
'not good',
'poor work',
'Could have done better.']

In [114]:
for i in docs:
    print(i)

Well done!
Good work
Great effort
nice work
Excellent!
Weak
Poor effort!
not good
poor work
Could have done better.


In [115]:
###  taking vocabulary(dictionary size())

voc_size = 100
Embed_docs = [one_hot(d,voc_size) for d in docs]
print(Embed_docs)


[[21, 51], [71, 59], [1, 71], [49, 59], [50], [42], [9, 71], [37, 71], [9, 59], [96, 86, 51, 13]]


### padding concepts 

In [116]:
## sentence should be of same length

sent_length = 5

Embd_doc_pad = pad_sequences(Embed_docs,maxlen=sent_length,padding='post')

print(Embd_doc_pad)




[[21 51  0  0  0]
 [71 59  0  0  0]
 [ 1 71  0  0  0]
 [49 59  0  0  0]
 [50  0  0  0  0]
 [42  0  0  0  0]
 [ 9 71  0  0  0]
 [37 71  0  0  0]
 [ 9 59  0  0  0]
 [96 86 51 13  0]]


In [117]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Flatten,Activation,Dense
from tensorflow.keras.activations import sigmoid,relu

In [118]:
model = Sequential()
model.add(Embedding(voc_size,8,input_length=sent_length))
model.add(Flatten())
model.add(Dense(1,activation = 'sigmoid'))

In [119]:
label = [1,1,1,1,1,0,0,0,0,0]

In [120]:
import numpy as np
label = np.array(label)

In [121]:
label

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [122]:
model.compile(optimizer = 'adam',metrics=['acc'],loss='binary_crossentropy')

In [123]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 5, 8)              800       
_________________________________________________________________
flatten (Flatten)            (None, 40)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 41        
Total params: 841
Trainable params: 841
Non-trainable params: 0
_________________________________________________________________


In [124]:
model.fit(Embd_doc_pad,label,epochs = 100,verbose = 2)

Epoch 1/100
1/1 - 0s - loss: 0.6956 - acc: 0.4000
Epoch 2/100
1/1 - 0s - loss: 0.6943 - acc: 0.4000
Epoch 3/100
1/1 - 0s - loss: 0.6931 - acc: 0.5000
Epoch 4/100
1/1 - 0s - loss: 0.6918 - acc: 0.5000
Epoch 5/100
1/1 - 0s - loss: 0.6906 - acc: 0.5000
Epoch 6/100
1/1 - 0s - loss: 0.6893 - acc: 0.5000
Epoch 7/100
1/1 - 0s - loss: 0.6881 - acc: 0.7000
Epoch 8/100
1/1 - 0s - loss: 0.6869 - acc: 0.7000
Epoch 9/100
1/1 - 0s - loss: 0.6857 - acc: 0.6000
Epoch 10/100
1/1 - 0s - loss: 0.6844 - acc: 0.6000
Epoch 11/100
1/1 - 0s - loss: 0.6832 - acc: 0.6000
Epoch 12/100
1/1 - 0s - loss: 0.6820 - acc: 0.7000
Epoch 13/100
1/1 - 0s - loss: 0.6808 - acc: 0.7000
Epoch 14/100
1/1 - 0s - loss: 0.6795 - acc: 0.7000
Epoch 15/100
1/1 - 0s - loss: 0.6783 - acc: 0.7000
Epoch 16/100
1/1 - 0s - loss: 0.6771 - acc: 0.7000
Epoch 17/100
1/1 - 0s - loss: 0.6758 - acc: 0.7000
Epoch 18/100
1/1 - 0s - loss: 0.6746 - acc: 0.8000
Epoch 19/100
1/1 - 0s - loss: 0.6733 - acc: 0.8000
Epoch 20/100
1/1 - 0s - loss: 0.6721 - a

In [130]:
import warnings
warnings.filterwarnings("ignore")

In [131]:
a = model.predict_classes(Embd_doc_pad)[0]

In [132]:
a

array([1])

In [137]:
a1 = model.predict_classes(Embd_doc_pad)[9]

In [138]:
a1

array([0])

In [139]:
model.predict(Embd_doc_pad)

array([[0.6597728 ],
       [0.61393094],
       [0.5270649 ],
       [0.64844984],
       [0.5546305 ],
       [0.4348277 ],
       [0.40499747],
       [0.4025321 ],
       [0.52934754],
       [0.30282515]], dtype=float32)

### Passing a test_case

In [140]:
c = ['Bangalore Hyderabad']
voc_size = 100
Embed_docs = [one_hot(f,voc_size) for f in c]
print(Embed_docs)

[[91, 70]]


In [141]:

sent_length = 5

Embd_doc_pad = pad_sequences(Embed_docs,maxlen=sent_length,padding='post')

print(Embd_doc_pad)


[[91 70  0  0  0]]


In [142]:
model.predict(Embd_doc_pad)

array([[0.53349686]], dtype=float32)

In [143]:
model.predict_classes(Embd_doc_pad)

array([[1]])

### spam detection using LSTM

In [144]:
import numpy as np
import pandas as pd

In [145]:
df = pd.read_csv("spam.csv")

In [146]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [147]:
df = df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)

In [148]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [149]:
df['v1'] = df['v1'].map({'ham':1,'spam':0}).astype(int)

In [150]:
df.head()

v1                                                 v2
0   1  Go until jurong point, crazy.. Available only ...
1   1                      Ok lar... Joking wif u oni...
2   0  Free entry in 2 a wkly comp to win FA Cup fina...
3   1  U dun say so early hor... U c already then say...
4   1  Nah I don't think he goes to usf, he lives aro...

In [151]:
df['v1'].unique()

array([1, 0])

In [152]:
df['v1'].value_counts()

1    4825
0     747
Name: v1, dtype: int64

In [153]:
df = df.rename(columns = {'v1':'output','v2':'E_mail_data'})

In [154]:
df.head()

output                                        E_mail_data
0       1  Go until jurong point, crazy.. Available only ...
1       1                      Ok lar... Joking wif u oni...
2       0  Free entry in 2 a wkly comp to win FA Cup fina...
3       1  U dun say so early hor... U c already then say...
4       1  Nah I don't think he goes to usf, he lives aro...

In [155]:
import re
import nltk
from nltk.stem import PorterStemmer,WordNetLemmatizer

In [156]:
ps = PorterStemmer()
ls = WordNetLemmatizer()

In [157]:
from nltk.corpus import stopwords

In [158]:
c = []
for i in range(len(df)):
    solution = re.sub('[^a-zA-Z]',' ',df['E_mail_data'][i])
    solution = solution.lower()
    solution = solution.split()
    solution = [ps.stem(k) for k in solution if k not in stopwords.words("english")]
    solution = ' '.join(solution)
    c.append(solution)
    
    
    

In [159]:
df['E_mail_data'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [160]:
c[0]

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [161]:
import tensorflow

In [162]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [163]:
voc_siz = 1000


In [164]:
email_data = [one_hot(data,voc_siz) for data in c]

In [165]:
email_data

[[393,
  539,
  692,
  826,
  73,
  844,
  592,
  451,
  900,
  893,
  325,
  862,
  651,
  116,
  542,
  855],
 [182, 460, 353, 474, 321, 749],
 [797,
  174,
  579,
  615,
  82,
  888,
  676,
  436,
  430,
  430,
  826,
  598,
  888,
  382,
  174,
  751,
  970,
  724,
  11,
  324,
  659],
 [321, 338, 620, 558, 665, 321, 324, 983, 620],
 [301, 216, 914, 37, 221, 854, 543],
 [661, 63, 343, 35, 73, 107, 414, 191, 386, 576, 182, 710, 970, 465, 184, 515],
 [153, 128, 414, 9, 588, 414, 551, 549],
 [241, 262, 163, 163, 112, 212, 471, 163, 512, 267, 174, 963, 723, 902, 267],
 [397, 933, 302, 866, 166, 849, 815, 42, 80, 574, 80, 62, 686, 687, 701],
 [564, 838, 321, 535, 394, 61, 327, 422, 564, 1, 797, 574, 564, 61, 752, 797],
 [103, 136, 577, 849, 31, 600, 21, 490, 98, 890, 691, 923],
 [20,
  655,
  82,
  133,
  65,
  724,
  172,
  184,
  436,
  912,
  51,
  51,
  789,
  659,
  140,
  772,
  606],
 [873,
  35,
  797,
  638,
  815,
  11,
  724,
  73,
  80,
  324,
  711,
  453,
  878,
  45,
  38

In [166]:
c = []
for i in email_data:
    c.append(len(i))
print(c)


print("checking highest length value")

print(max(c))

[16, 6, 21, 9, 7, 16, 8, 15, 15, 16, 12, 17, 17, 15, 2, 16, 3, 11, 7, 21, 3, 6, 6, 14, 5, 15, 3, 12, 7, 7, 9, 16, 3, 5, 13, 13, 5, 4, 4, 11, 9, 11, 16, 1, 9, 4, 5, 4, 8, 15, 5, 17, 10, 21, 18, 8, 18, 4, 2, 5, 9, 8, 3, 6, 18, 12, 13, 16, 7, 4, 6, 2, 7, 3, 2, 4, 6, 5, 3, 6, 3, 3, 5, 2, 3, 5, 12, 16, 4, 8, 6, 18, 21, 9, 15, 13, 6, 5, 21, 6, 13, 8, 15, 19, 7, 9, 4, 8, 12, 4, 3, 3, 16, 16, 18, 16, 14, 10, 9, 12, 16, 5, 16, 5, 5, 2, 17, 1, 19, 4, 1, 5, 3, 17, 25, 5, 2, 4, 19, 11, 3, 3, 19, 4, 4, 6, 19, 9, 3, 5, 3, 9, 4, 15, 35, 2, 2, 10, 11, 13, 10, 7, 6, 18, 21, 7, 14, 9, 8, 7, 7, 16, 3, 13, 7, 7, 4, 17, 6, 12, 14, 3, 5, 2, 4, 13, 3, 10, 5, 13, 9, 18, 4, 10, 8, 6, 4, 8, 13, 4, 4, 12, 20, 3, 4, 10, 16, 5, 10, 5, 6, 3, 5, 3, 3, 6, 5, 7, 3, 13, 5, 17, 3, 19, 14, 7, 22, 5, 19, 3, 15, 4, 4, 6, 22, 6, 7, 2, 16, 14, 6, 6, 6, 23, 4, 5, 3, 5, 14, 20, 7, 27, 0, 18, 4, 7, 6, 2, 14, 6, 1, 11, 5, 15, 3, 4, 6, 23, 4, 15, 5, 18, 18, 6, 3, 1, 5, 3, 4, 6, 3, 4, 4, 1, 14, 7, 1, 19, 14, 20, 5, 9, 3, 2, 5, 19,

In [167]:
sent_length = 77
email_data_pad = pad_sequences(email_data,maxlen = sent_length,padding = 'post')
print(email_data_pad)

[[393 539 692 ...   0   0   0]
 [182 460 353 ...   0   0   0]
 [797 174 579 ...   0   0   0]
 ...
 [706 969 755 ...   0   0   0]
 [371 448 174 ...   0   0   0]
 [367 231 893 ...   0   0   0]]


In [168]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation,Flatten,Dropout,Embedding,LSTM,Bidirectional
from tensorflow.keras.activations import sigmoid,relu

In [169]:
model = Sequential()
model.add(Embedding(voc_siz,10,input_length=sent_length))
model.add(LSTM(50))
model.add(Dense(1 , activation = 'sigmoid'))


In [170]:
model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['acc'])

### Bidirectional_RNN(LSTM)

In [171]:
model = Sequential()
model.add(Embedding(voc_siz,10,input_length=sent_length))
model.add(Bidirectional(LSTM(50)))
model.add(Dense(1 , activation = 'sigmoid'))

In [172]:
model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['acc'])

In [173]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 77, 10)            10000     
_________________________________________________________________
bidirectional (Bidirectional (None, 100)               24400     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 34,501
Trainable params: 34,501
Non-trainable params: 0
_________________________________________________________________


In [174]:
X = np.array(email_data_pad)
y = np.array(df['output'])

In [175]:
X

array([[393, 539, 692, ...,   0,   0,   0],
       [182, 460, 353, ...,   0,   0,   0],
       [797, 174, 579, ...,   0,   0,   0],
       ...,
       [706, 969, 755, ...,   0,   0,   0],
       [371, 448, 174, ...,   0,   0,   0],
       [367, 231, 893, ...,   0,   0,   0]])

In [176]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [177]:
from sklearn.model_selection import train_test_split

In [178]:
X_train,X_test,y_train,y_test = train_test_split(X , y,test_size = 0.33,random_state = 11)

In [179]:
len(X_test) , len(y_test)

(1839, 1839)

In [180]:
len(X_train) , len(y_train)

(3733, 3733)

In [181]:
model.fit(X_train,y_train,validation_data = (X_test,y_test),verbose = 2 , batch_size = 64 , epochs = 20)

Epoch 1/20
59/59 - 6s - loss: 0.4398 - acc: 0.8535 - val_loss: 0.2801 - val_acc: 0.8766
Epoch 2/20
59/59 - 4s - loss: 0.1834 - acc: 0.9309 - val_loss: 0.1152 - val_acc: 0.9652
Epoch 3/20
59/59 - 4s - loss: 0.0884 - acc: 0.9754 - val_loss: 0.0703 - val_acc: 0.9782
Epoch 4/20
59/59 - 5s - loss: 0.0584 - acc: 0.9834 - val_loss: 0.0644 - val_acc: 0.9837
Epoch 5/20
59/59 - 5s - loss: 0.0411 - acc: 0.9896 - val_loss: 0.0673 - val_acc: 0.9826
Epoch 6/20
59/59 - 4s - loss: 0.0364 - acc: 0.9914 - val_loss: 0.0692 - val_acc: 0.9826
Epoch 7/20
59/59 - 5s - loss: 0.0310 - acc: 0.9928 - val_loss: 0.0661 - val_acc: 0.9848
Epoch 8/20
59/59 - 4s - loss: 0.0242 - acc: 0.9949 - val_loss: 0.0681 - val_acc: 0.9842
Epoch 9/20
59/59 - 4s - loss: 0.0206 - acc: 0.9952 - val_loss: 0.0673 - val_acc: 0.9821
Epoch 10/20
59/59 - 4s - loss: 0.0167 - acc: 0.9962 - val_loss: 0.0813 - val_acc: 0.9799
Epoch 11/20
59/59 - 4s - loss: 0.0137 - acc: 0.9971 - val_loss: 0.0726 - val_acc: 0.9815
Epoch 12/20
59/59 - 4s - loss:

In [182]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [183]:
import warnings
warnings.filterwarnings("ignore")

In [184]:
y_train_pred = model.predict_classes(X_train)

In [185]:
y_test_pred = model.predict_classes(X_test)

In [186]:
accuracy_score(y_train,y_train_pred) * 100

99.7589070452719

In [187]:
accuracy_score(y_test,y_test_pred) * 100

98.20554649265905

In [188]:
confusion_matrix(y_train,y_train_pred)

array([[ 511,    9],
       [   0, 3213]], dtype=int64)

In [189]:
confusion_matrix(y_test,y_test_pred)

array([[ 207,   20],
       [  13, 1599]], dtype=int64)

In [190]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.94      0.91      0.93       227
           1       0.99      0.99      0.99      1612

    accuracy                           0.98      1839
   macro avg       0.96      0.95      0.96      1839
weighted avg       0.98      0.98      0.98      1839



In [191]:
a = ['hai i am offering a job']


In [192]:
a

['hai i am offering a job']

In [193]:
email_data1 = [one_hot(l,voc_siz) for l in a]

In [194]:
sent_length = 77
email_data_pad1 = pad_sequences(email_data1,maxlen = sent_length,padding = 'post')
print(email_data_pad1)

[[157 410 329 746 678 673   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0]]


### The test case prediction probability rate 

In [196]:
model.predict(email_data_pad1)

array([[0.9985163]], dtype=float32)

### Test case Predicition label

In [197]:
model.predict_classes(email_data_pad1)

array([[1]])